// <auto-generated />
using System;
using CarDealership.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarDealership.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarDealership.Models.Advertisement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarVIN")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Car_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonPesel")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Salesman")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarVIN");

                    b.HasIndex("PersonPesel");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("CarDealership.Models.Car", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(17)")
                        .HasMaxLength(17);

                    b.Property<bool>("AC")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Combustion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ESP")
                        .HasColumnType("bit");

                    b.Property<int>("Engine")
                        .HasColumnType("int")
                        .HasMaxLength(6);

                    b.Property<bool>("GPS")
                        .HasColumnType("bit");

                    b.Property<string>("Gearbox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HP")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<int>("Mileage")
                        .HasColumnType("int")
                        .HasMaxLength(8);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ParkAssist")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ProductionYear")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Shift_Paddles")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VIN");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarDealership.Models.Person", b =>
                {
                    b.Property<int>("Pesel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Pesel");

                    b.ToTable("People");
                });

            modelBuilder.Entity("CarDealership.Models.Advertisement", b =>
                {
                    b.HasOne("CarDealership.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarVIN");

                    b.HasOne("CarDealership.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonPesel");
                });
#pragma warning restore 612, 618
        }
    }
}
